archives:
  - format: tar.gz
    replacements:
      amd64: x86_64
      darwin: macOS
      linux: Linux
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip

build:
  binary: sbu
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: windows
      goarch: arm64
    - goos: linux
      goarch: arm64
  main: .

dockers:
 - image_templates:
    - "eugenmayer/sbu:latest"
    - "eugenmayer/sbu:{{ .Version }}"

universal_binaries:
  - replace: true
